// Generated by CoffeeScript 1.9.3
var Kefir, deepExtend, default_options, defaults, fetch$, makeQueryString, timeoutPromise;

Kefir = require('kefir');

deepExtend = function(o1, o2) {
  var k, v, v1;
  for (k in o2) {
    v = o2[k];
    if (v1 = o1[k] && typeof v1 === 'object' && typeof v === 'object') {
      o1[k] = deepExtend(v1, v);
    } else {
      o1[k] = v;
    }
  }
  return o1;
};

defaults = function(o1, o2) {
  var k, v;
  for (k in o2) {
    v = o2[k];
    if (o1[k] == null) {
      o1[k] = v;
    }
  }
  return o1;
};

makeQueryString = function(query) {
  var k, s, v;
  s = "?";
  for (k in query) {
    v = query[k];
    if (v != null) {
      s += k + "=" + v + "&";
    }
  }
  return s;
};

timeoutPromise = function(context, p, ms) {
  return new Promise(function(resolve, reject) {
    var clear_rej, clear_res, timeout_timeout;
    timeout_timeout = setTimeout(function() {
      var response;
      response = {
        error: "Request timed out"
      };
      Object.assign(response, context);
      return reject(response);
    }, ms);
    clear_res = function(res) {
      clearTimeout(timeout_timeout);
      return resolve(res);
    };
    clear_rej = function(rej) {
      clearTimeout(timeout_timeout);
      return reject(rej);
    };
    return p.then(clear_res, clear_rej);
  });
};

default_options = {
  headers: {
    'Accept': 'application/json',
    'Content-Type': 'application/json'
  },
  credentials: 'same-origin'
};

fetch$ = function(method, url, options) {
  var base_url, body, context, fetch_promise, query, timeout;
  if (options == null) {
    options = {};
  }
  options.method = method;
  if (query = options.query) {
    url += makeQueryString(query);
    delete options.query;
  }
  if (body = options.body) {
    options.body = JSON.stringify(body);
  }
  options = defaults(options, default_options);
  context = {
    method: method,
    url: url,
    query: query,
    body: body
  };
  if (base_url = options.base_url) {
    url = base_url + url;
  }
  fetch_promise = fetch(url, options).then(function(res) {
    if (res.status === 200) {
      return res.json()["catch"](function(err) {
        return Promise.reject("Could not parse response");
      });
    } else {
      return res.text().then(function(json_string) {
        var e, json;
        if (!json_string.length) {
          return "Error " + res.status + " with no response";
        }
        try {
          json = JSON.parse(json_string);
          return json;
        } catch (_error) {
          e = _error;
          return {
            error: json_string
          };
        }
      }).then(function(response) {
        Object.assign(response, context);
        return Promise.reject(response);
      });
    }
  });
  if (timeout = options.timeout) {
    fetch_promise = timeoutPromise(context, fetch_promise, timeout);
  }
  return Kefir.fromPromise(fetch_promise);
};

fetch$.setDefaultOptions = function(options) {
  return defaults(default_options, defaults);
};

module.exports = fetch$;
